"""Changing unique constraint for the title as more notes an have same title

Revision ID: 2bb7a24cba09
Revises: 6ff3ed9e6246
Create Date: 2020-02-21 02:01:03.640175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb7a24cba09'
down_revision = '6ff3ed9e6246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_title', table_name='notes')
    op.create_index(op.f('ix_notes_title'), 'notes', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_title'), table_name='notes')
    op.create_index('ix_notes_title', 'notes', ['title'], unique=1)
    # ### end Alembic commands ###
